# Generated by Django 2.2.3 on 2019-07-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='pwd',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(default='匿名', max_length=20),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='openid',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
