# Generated by Django 2.2.3 on 2019-07-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190719_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classificationhistory',
            old_name='imagedate',
            new_name='image_date',
        ),
        migrations.RenameField(
            model_name='classificationhistory',
            old_name='imagekind',
            new_name='image_kind',
        ),
        migrations.RenameField(
            model_name='classificationhistory',
            old_name='imagepath',
            new_name='image_path',
        ),
        migrations.RenameField(
            model_name='classificationhistory',
            old_name='imagetype',
            new_name='image_type',
        ),
        migrations.AddField(
            model_name='classificationhistory',
            name='image_md5',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='classificationhistory',
            table='upload_image',
        ),
    ]
